package Model.Hibernate;
// Generated Oct 24, 2019, 11:20:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer numClient;
     private Province province;
     private String nomClient;
     private String prenomClient;
     private String telClient;
     private String adresseClient;
     private Set<Commande> commandes = new HashSet<Commande>(0);

    public Client() {
    }

	
    public Client(Province province, String nomClient, String prenomClient, String telClient, String adresseClient) {
        this.province = province;
        this.nomClient = nomClient;
        this.prenomClient = prenomClient;
        this.telClient = telClient;
        this.adresseClient = adresseClient;
    }
    public Client(Province province, String nomClient, String prenomClient, String telClient, String adresseClient, Set<Commande> commandes) {
       this.province = province;
       this.nomClient = nomClient;
       this.prenomClient = prenomClient;
       this.telClient = telClient;
       this.adresseClient = adresseClient;
       this.commandes = commandes;
    }
   
    public Integer getNumClient() {
        return this.numClient;
    }
    
    public void setNumClient(Integer numClient) {
        this.numClient = numClient;
    }
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    public String getNomClient() {
        return this.nomClient;
    }
    
    public void setNomClient(String nomClient) {
        this.nomClient = nomClient;
    }
    public String getPrenomClient() {
        return this.prenomClient;
    }
    
    public void setPrenomClient(String prenomClient) {
        this.prenomClient = prenomClient;
    }
    public String getTelClient() {
        return this.telClient;
    }
    
    public void setTelClient(String telClient) {
        this.telClient = telClient;
    }
    public String getAdresseClient() {
        return this.adresseClient;
    }
    
    public void setAdresseClient(String adresseClient) {
        this.adresseClient = adresseClient;
    }
    public Set<Commande> getCommandes() {
        return this.commandes;
    }
    
    public void setCommandes(Set<Commande> commandes) {
        this.commandes = commandes;
    }




}


