package Model.Hibernate;
// Generated Oct 24, 2019, 11:20:08 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Commande generated by hbm2java
 */
public class Commande  implements java.io.Serializable {


     private Integer numCommande;
     private Client client;
     private Date dateCommande;
     private boolean livree;
     private Set<Contient> contients = new HashSet<Contient>(0);

    public Commande() {
    }

	
    public Commande(Client client, Date dateCommande, boolean livree) {
        this.client = client;
        this.dateCommande = dateCommande;
        this.livree = livree;
    }
    public Commande(Client client, Date dateCommande, boolean livree, Set<Contient> contients) {
       this.client = client;
       this.dateCommande = dateCommande;
       this.livree = livree;
       this.contients = contients;
    }
   
    public Integer getNumCommande() {
        return this.numCommande;
    }
    
    public void setNumCommande(Integer numCommande) {
        this.numCommande = numCommande;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getDateCommande() {
        return this.dateCommande;
    }
    
    public void setDateCommande(Date dateCommande) {
        this.dateCommande = dateCommande;
    }
    public boolean isLivree() {
        return this.livree;
    }
    
    public void setLivree(boolean livree) {
        this.livree = livree;
    }
    public Set<Contient> getContients() {
        return this.contients;
    }
    
    public void setContients(Set<Contient> contients) {
        this.contients = contients;
    }




}


