package Model.Hibernate;
// Generated Oct 24, 2019, 11:20:08 PM by Hibernate Tools 4.3.1



/**
 * Contient generated by hbm2java
 */
public class Contient  implements java.io.Serializable {


     private Integer numContient;
     private Commande commande;
     private Materiels materiels;
     private int quantiteCommande;

    public Contient() {
    }

    public Contient(Commande commande, Materiels materiels, int quantiteCommande) {
       this.commande = commande;
       this.materiels = materiels;
       this.quantiteCommande = quantiteCommande;
    }
   
    public Integer getNumContient() {
        return this.numContient;
    }
    
    public void setNumContient(Integer numContient) {
        this.numContient = numContient;
    }
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }
    public Materiels getMateriels() {
        return this.materiels;
    }
    
    public void setMateriels(Materiels materiels) {
        this.materiels = materiels;
    }
    public int getQuantiteCommande() {
        return this.quantiteCommande;
    }
    
    public void setQuantiteCommande(int quantiteCommande) {
        this.quantiteCommande = quantiteCommande;
    }




}


