package Model.Hibernate;
// Generated Oct 26, 2019, 5:40:20 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Materiels generated by hbm2java
 */
public class Materiels  implements java.io.Serializable {


     private int numSerie;
     private Categorie categorie;
     private String nomMateriels;
     private float prixMateriels;
     private int quantiteStock;
     private Set<Contient> contients = new HashSet<Contient>(0);

    public Materiels() {
    }

	
    public Materiels(int numSerie, Categorie categorie, String nomMateriels, float prixMateriels, int quantiteStock) {
        this.numSerie = numSerie;
        this.categorie = categorie;
        this.nomMateriels = nomMateriels;
        this.prixMateriels = prixMateriels;
        this.quantiteStock = quantiteStock;
    }
    public Materiels(int numSerie, Categorie categorie, String nomMateriels, float prixMateriels, int quantiteStock, Set<Contient> contients) {
       this.numSerie = numSerie;
       this.categorie = categorie;
       this.nomMateriels = nomMateriels;
       this.prixMateriels = prixMateriels;
       this.quantiteStock = quantiteStock;
       this.contients = contients;
    }
   
    public int getNumSerie() {
        return this.numSerie;
    }
    
    public void setNumSerie(int numSerie) {
        this.numSerie = numSerie;
    }
    public Categorie getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(Categorie categorie) {
        this.categorie = categorie;
    }
    public String getNomMateriels() {
        return this.nomMateriels;
    }
    
    public void setNomMateriels(String nomMateriels) {
        this.nomMateriels = nomMateriels;
    }
    public float getPrixMateriels() {
        return this.prixMateriels;
    }
    
    public void setPrixMateriels(float prixMateriels) {
        this.prixMateriels = prixMateriels;
    }
    public int getQuantiteStock() {
        return this.quantiteStock;
    }
    
    public void setQuantiteStock(int quantiteStock) {
        this.quantiteStock = quantiteStock;
    }
    public Set<Contient> getContients() {
        return this.contients;
    }
    
    public void setContients(Set<Contient> contients) {
        this.contients = contients;
    }




}


